---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - redhat:
      value: redhat_best_fit_cluster
  - vmware:
      value: vmware_cust_placement
  - microsoft:
      value: microsoft_best_fit_least_utilized
