---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - approval_type:
      value: require_approval
  - ValidateRequest:
      on_error: pending_request
